<section class="productPage">
    <div class="inner">
        <article class="content">
            <h2> <span> Sensus </span> The MeiStream®  FS Flow Sensor 90 °C</h2>

            <p>The MeiStream® FS Flow Sensor 90 °C combines the high reliability and measurement accuracy of the Woltman WP meter with the advantages of the Woltman WS meter in the lower measuring range. This combination creates an excellent flow sensor with an MID approval according to MI004 or EN 1434 in the accuracy class 2.</p>
            <p>Volume pulses are generated by the interface HRI-Mei FS. This interface transfers volume pulses with programmable pulse values to the heating or cooling calculator. Possible reverse flows are compensated.</p>
            <h4>Benefits to you</h4>
            <ul>
                <li>Provides excellent metrological performance</li>
                <li>Installs in a horizontal or vertical position</li>
                <li>Easy installation, even in narrow locations</li>
                <li>Measures cooling water starting from 5 °C</li>
                <li>Compatible with existing measuring points</li>
                <li>Does not require straight pipe at inlet or outlet (U0D0 acc. EN 14154)</li>
                <li>Measures hot process water up to 90 °C</li>
            </ul>
        </article>
        <div class="img">
            <img src="/assets/images/meters/thermal.png" alt="MeiStream® Meter">
            <a target="_blank" href="/assets/pdf/EN-MeiStreamFSDataSheet.pdf">The MeiStream® Product PDF</a>
        </div>
        

    </div>
</section>

<section class="productPage extraBottomPadding">
    <div class="inner">
        <div class="img leftAlign">
            <img class="img" src="/assets/images/pollustat-thermal-energy-meter.png" alt="Sensus Pollustar Thermal Energy Meter">
            <a target="_blank" href="/assets/pdf/EN-PolluStatDataSheet.pdf">Pollustat® Product PDF</a>
        </div>

        <article class="content">
            <h2> <span> Sensus </span> Pollustat®</h2>

            <p>The compact PolluStat® thermal energy meter is used to measure energy consumption in heating or cooling circuits. Due to its high-precision flow sensor, the application range reaches from district heating to consumption billing for individual apartments.</p>
            <h4>Integrated data logger</h4>
            <p>Hourly, daily and monthly measurement values are stored in the meter’s memory. All data from the archive can be read only by means of remote reading.  You can also view the last month’s data logger records on the display.</p>
            <p>All parameter values are recorded in the heat meter’s memory. The data logger capacity is:</p>
            <ul>
                <li>Up to 960 h – for hourly records</li>
                <li>Up to 1116 days – for daily records</li>
                <li>Up to 36 last months – for monthly records</li>
            </ul>
            <p>The archive data storage time is no less than 36 months and it keeps the stored data even if the device is disconnected from the power supply.</p>
            <h4>Benefits to you</h4>
            <ul>
                <li>Is equipped with an easy-to-read LCD display with an eight-digit main reading line;  some addi tional symbols support the readout.</li>
                <li>Provides a removable calculator for installation in narrow places</li>
                <li>Updates measuring values quickly</li>
            </ul>
        </article>
    </div>
</section>